### ISSUE TITLE
Watch for hovered item not working

### ISSUE THREAD

**Issue by Cort69** [fmauNeko/MarketBoardPlugin#39] opened 2022-07-25 13:18 UTC
Hovering over item search function used to work just fine until last update. Now in order for it to work I need to disable and enable the plugin every time in game. How can I fix this?

**Comment by Pythyu** [comment] 2022-07-25 13:57
uhmmm, it's working perfectly fine for me :/
Did you try to uninstall the plugins, check that he is correctly deleted from your installedPlugin folder and reinstall it ?

**Comment by Cort69** [comment] 2022-07-25 14:22
How do I go about uninstalling the plugin and checking that it is correctly deleted from the installed plugin folder? Thank you in advance.

**Comment by Pythyu** [comment] 2022-07-25 15:01
(My game's in french so you'll have to look at where i click x') )
Here a record to uninstall ingame : 

https://user-images.githubusercontent.com/45374460/180808858-aa4c1304-795e-4cf3-b84f-bb28e47d0736.mp4

Once it's done go to C:\Users\<your_user>\AppData\Roaming\XIVLauncher\installedPlugins
And delete the folder MarketBoardPlugin
Next  go to C:\Users\<your_user>\AppData\Roaming\XIVLauncher\pluginConfigs
And delete the file MarketBoardPlugin.json

Restart your game and install the plugin via dalamud as usual and you should have a clean install

**Comment by Pythyu** [comment] 2022-07-25 15:07
I did the same process just in case and hovering is still working perfectly for me

**Comment by Viverea** [comment] 2022-07-26 10:44
Hi @Cort69, did you have anything in your search bar when your hover stops working? Just checking to see if you might be encountering the same behavior as I did: https://github.com/fmauNeko/MarketBoardPlugin/issues/31#issuecomment-1195316317

**Comment by Pythyu** [comment] 2022-07-26 13:45
Do you have still the issue or it's fixed then @Viverea ? =)

**Comment by Pythyu** [comment] 2022-07-26 13:49
@Viverea I misunderstood your issue as well mb, I'm gonna check that out. I believe you still have it ?

**Comment by Pythyu** [comment] 2022-07-26 13:56
Yea confirmed the issue =), I'll look to fix that.

**Comment by Pythyu** [comment] 2022-07-28 02:09
@Cort69 are you still having the issue ?

**Comment by Cort69** [comment] 2022-07-28 09:45
@Pythyu For me, it's still occurring. So if I launch the plugin using /pmb hovering over an item doesn't automatically search for said item like it used to prior to the latest update. I have to go to the Dalamud plugins manually disable and enable the plugin for the hover over search function to begin to work. It continues to work until I log off. Whenever I log in again, have to disable/enable.

**Comment by Pythyu** [comment] 2022-07-28 12:56
Did you do what I showed you ? to hard reset your plugin installation ?

**Comment by Cort69** [comment] 2022-07-29 18:43
@Pythyu Yes it's still doing it. Deleted the plugin and reinstalled and the issue remains  (T_T )/'

**Comment by Pythyu** [comment] 2022-07-30 01:27
@Cort69  Ok I might need to look more in details on that then, hit me up on discord : Marethyu#4284
This way i can more easily identify what's wrong

**Comment by Rulqu** [comment] 2022-08-09 12:18
This is happening to me too. I either have to restart client or disable/enable the plugin to make it work.

**Comment by Pythyu** [comment] 2022-08-09 14:17
@Rulqu Hit me up on discord : Marethyu#4284 so i can look in more details into it bc i can't reproduce the issue :x

**Comment by Emberblink** [comment] 2022-08-14 15:13
had the same issue. helped @Pythyu  with it

**Comment by Pythyu** [comment] 2022-08-14 15:20
Fixed in #41 

Thanks a lot to @Emberblink for helping me out.
If you have the same problem and the PR is not merged yet here is a fixed build :

[link](https://cdn.discordapp.com/attachments/1007979085152125000/1008388887464399008/latest.zip)

**Comment by Pythyu** [comment] 2022-08-30 09:27
@fmauNeko issue solved by #41 and merged
you can close the issue

**Closed** 2022-08-30 11:40 UTC
