### ISSUE TITLE
I cant find MBP in the plugins list

### ISSUE THREAD

**Issue by subjadeites** [fmauNeko/MarketBoardPlugin#22] opened 2021-12-11 07:03 UTC
get testing and out of testing both have no MBP
![20211211150045](https://user-images.githubusercontent.com/58224835/145667786-3d7722eb-313d-4fb7-b674-901ede29dd93.jpg)

**Comment by n3farious** [comment] 2021-12-11 17:03
Duplicate of #21

**Comment by xKillerbees** [comment] 2021-12-12 06:07
Well #21 I think was the original 6.0 update that would crash the game, this one could be focused on fixing the new bug so the team would remove it from the blocked list.

**Comment by CodingSheep** [comment] 2021-12-12 17:24
If you enable "Get plugin testing builds" under Settings > Experimental, the plugin will show up on the list as it seems to currently be in the 6.0 Testing Phase.

**Closed** 2021-12-14 13:01 UTC
