### ISSUE TITLE
Feature Request: Window size and position lock

### ISSUE THREAD

**Issue by randomap** [fmauNeko/MarketBoardPlugin#51] opened 2022-08-29 18:00 UTC
Hello I wanted to ask if you could add the ability to lock the position and size of the window. Thank you.

**Comment by Pythyu** [comment] 2022-08-29 20:10
Sure, I'll look into it ^^

**Comment by fmauNeko** [comment] 2022-08-29 21:52
Duplicate of #43

**Closed by fmauNeko** 2022-08-29 21:52 UTC
